name: Project progress

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-notifications-discord
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: "New update on BackEND Reposity! Merged"
          color: 0x00FF00
          url: "https://github.com/ZeveNor/EightyCCTV-core"
          title: "[Backend] EightyCCTV."
